### ISSUE TITLE
Cannot resolve normalized_image_path

### ISSUE THREAD

**Issue by henrytriplette** [wanadev/yoga#56]
## Current Behavior
When trying to optimize a glb file, application returns `ValueError: Cannot resolve *13` and quits

## Steps to Reproduce
1. Using latest Windows version - `yoga 1.3.1`
2. Using latest Windows version of Blender - `blender 4.0.2`
3. Using Blender glb/gltf exporter, export 3D model
4. Using Yoga, run `yoga model input.glb output.glb`

## Context (Environment)
- OS: Win 11
- Blender: 4.0.2
- Yoga: 1.3.1 / 1.3.0

## Detailed Error Log
```
Traceback (most recent call last):
  File "C:\yoga\yogawin.py", line 6, in <module>
  File "C:\yoga\yoga\__main__.py", line 25, in main
  File "C:\yoga\concurrent\futures\_base.py", line 449, in result
  File "C:\yoga\concurrent\futures\_base.py", line 401, in __get_result
  File "C:\yoga\concurrent\futures\thread.py", line 58, in run
  File "C:\yoga\yoga\model\__init__.py", line 251, in optimize
  File "C:\yoga\yoga\model\helpers.py", line 135, in model_embed_images
ValueError: Cannot resolve *13
```

**Comment by flozz** [comment]
Hello,

Can you provide a 3D model that cause this error to allow me to reproduce? :)

**Comment by henrytriplette** [comment]
Sure thing, 

Here is the file [[LINK](https://mega.nz/file/S9MgmD7Y#4F7SuDTyyF5mBprSKXRbCeWKfOV6FVPIOcw5oKXXiYI)]

**Comment by flozz** [comment]
Ok, it seems we do not handle properly textures embedded in GLB... 

If I provide a fallback texture, it works bit the output files goes to 10 MB...

```
$ python -m yoga model --fallback-texture fallback.png issue56.glb out.glb
Warning: Cannot resolve *13, using the fallback texture instead.
Optimizing fallback texture...
Warning: Cannot resolve *14, using the fallback texture instead.
Warning: Cannot resolve *12, using the fallback texture instead.
Warning: Cannot resolve *10, using the fallback texture instead.
Warning: Cannot resolve *11, using the fallback texture instead.
Warning: Cannot resolve *9, using the fallback texture instead.
Warning: Cannot resolve *7, using the fallback texture instead.
Warning: Cannot resolve *8, using the fallback texture instead.
Warning: Cannot resolve *6, using the fallback texture instead.
Warning: Cannot resolve *4, using the fallback texture instead.
Warning: Cannot resolve *5, using the fallback texture instead.
Warning: Cannot resolve *3, using the fallback texture instead.
Warning: Cannot resolve *1, using the fallback texture instead.
Warning: Cannot resolve *2, using the fallback texture instead.
Warning: Cannot resolve *0, using the fallback texture instead.

$ ls -lh out.glb
-rw-rw-r-- 1 fabien fabien 9,6M janv. 12 16:35 out.glb
```

I am not good enough on the 3D/Assimp part to help more with this issue :/

---

Maybe related issues:
* https://github.com/wanadev/yoga/issues/21
* https://github.com/wanadev/yoga/issues/20

**Comment by flozz** [comment]
Also, there is noticeable changes between texture of the original GLB and the outputed one:

![image](https://github.com/wanadev/yoga/assets/971438/94b8f28b-61ba-4d77-bbe8-613fa67f5f88)
